# frontend/Dockerfile.dev
FROM node:20-bookworm-slim

#EStablecemos las variables que vamosa  recibir por argumento en al construccion
ARG NEXT_PUBLIC_AUTH_API_URL
ARG NEXT_PUBLIC_PRODUCT_API_URL
ARG NEXT_PUBLIC_PROVIDER_API_URL

# Evita problemas de permisos en contenedores
ENV NODE_ENV=development\
    NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL \
    NEXT_PUBLIC_PRODUCT_API_URL=$NEXT_PUBLIC_PRODUCT_API_URL \
    NEXT_PUBLIC_PROVIDER_API_URL=$NEXT_PUBLIC_PROVIDER_API_URL 
    
WORKDIR /app

# Instala dependencias si el build no usa bind mount (igual, el volumen las preservará)
COPY package*.json ./
RUN npm install -g npm@latest &&\
    npm install &&\
    npm install next@latest react@latest react-dom@latest

# Copia el resto (en tiempo de ejecución, el bind mount de compose sobrescribe /app)
COPY . .

EXPOSE 3000
CMD ["npm","run","dev"]